### ISSUE TITLE
Use on Android

### ISSUE THREAD

**Issue by ingnelson** [Snawoot/chunk-nordic#4]
Hi.
This looks great ! .
Can be possible to use this on Android as client and the server on a VPS to create a tunnel and use it like VPN ?
Can someone can create a app that allow http headers request, please ?
This way we can use it bypass firewall from ISP and many people can use this excellent program .

I hope your answers.

**Comment by Snawoot** [comment]
Hello!

I have no plans to develop a native Android application because I can't, I'm not mobile developer. However, it is possible to run chunk-nordic on Android via [Termux](https://play.google.com/store/apps/details?id=com.termux) application.

Here is commands which install chunk-nordic in Termux session:

```sh
pkg install python
pip install chunk-nordic
```

You'll need to run these commands only once.

Once done, you may run chunk-nordic: `chunk-client URL`. Of course, you can create shell script or even create Termux Widget to launch it conveniently.

Once started, it'll accept incoming connections on local port 1940. Note that if you'll use it for VPN, you'll have to exclude server IP address from VPN routes or otherwise underlying upstream connection of chunk-nordic will be looped back to the VPN tunnel.

Such approach with VPN and chunk-nordic may appear rather complex to deploy and maintain. Probably you will be better off with encrypted proxy via [steady-tun](https://github.com/Snawoot/steady-tun) (linux binary for ARM runs via Termux as well) or [ptw](https://github.com/Snawoot/ptw) on Android and haproxy + http or socks proxy on your VPS. Here is an [example of Docker deployment for such server](https://github.com/Snawoot/ptw/tree/master/docker_deploy/ptw-server). It is actually faster than VPN in most cases because of TCP buffering and separated packet loss handling between client, proxy and destination.

Or you may even try serverless option: https://github.com/Snawoot/hola-proxy
